#!/bin/sh

TICKETNUM=$(git branch | grep '^\* ' | grep -o '[A-Z]\+-[0-9]\+')

echo $TICKETNUM > $1
echo '
# 50-character subject line
#
# 72-character wrapped longer description. This should answer:
#
# * Why was this change necessary?
# * How does it address the problem?
# * Are there any side effects?
#
# Include a link to the ticket, if any.
#' >> $1