#!/usr/bin/env bash

# git this-month
#
# Print all commits that were made by the configured user
# since the first of the month
#

## BSD Date
since="$(date +%Y-%m)-01"

git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --since="$since 00:00" --author $(git config user.email)