#!/usr/bin/env bash

# Clean up local branches

function main() {
  if [ -z "$@" ]; then
   default=$(git branch | grep -Eo "(main|master)$")
  else
    default=$@
  fi
  git checkout $default
  git fetch -p
  git branch -vv | grep ': gone]' | awk '{ print $1; }' | xargs -n 1 git branch -D
}


isGitRepo && isWorktreeDirty && main "$@"