#!/usr/bin/env bash

## Get a list of commit authors, with the number of commits
# they have made, ordered by number of commits, the pretty
# primt it with awk

function main() {
  git shortlog --summary --numbered --no-merges | \
    awk -v cyan='\033[36m' -v feint='\033[2m' -v none='\033[0m' '{print cyan$2" "$3none " " feint$1none}'
}

isGitRepo && main