#!/usr/bin/env bash

# Git Squash
#
# Interactively rebase the current branches commits
# from where it was forked from its base branch (assumed
# to be develop, but can be passed as an arg),
#
# Primarily useful for tidying up before pushing and
# creating a PR.

function head() {
  git rev-parse --abbrev-ref HEAD
}

function forkpoint() {
  git branch | grep -Eo "(develop|main|master)$"
}


function main() {
  if [ -z "$@" ]; then
    forkPoint="$(forkpoint)"
  else
    forkPoint="$@"
  fi
  git rebase -i --autosquash $(git merge-base --fork-point "$forkPoint" $(head))
}

git rev-parse --git-dir > /dev/null 2>&1 && main "$@"