#!/usr/bin/env bash

# git this-year
#
# Print all commits that were made by the configured user
# since the first of January this year
#

since="$(date +%Y)-01-01"

git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --since="$since 00:00" --author $(git config user.email)