#!/usr/bin/env bash

# git rewrite

# An alternative to git squash that will
# do a soft reset back to a given point,
# then allow you to rewrite the history of the
# rolled back commits so you can make it
# look like a much nice history.
#

numberRegex='^[0-9]+$'

function main() {
  git reset --soft "$@"
}


if [ -z "$@" ]; then
  main "develop"
else
  if [[ "$@" =~ $numberRegex ]] ; then
    rollback="HEAD~$@"
  else
    rollback=$(git merge-base --fork-point "$@" $(git rev-parse --abbrev-ref HEAD))
  fi
  main "$rollback"
fi