#!/usr/bin/env bash

# git last-week
#
# Print all commits that were made by the configured user
# last calendar week
#

## BSD date command (Mac)
# after="$(date -v-mon -v-sun -v-mon +%Y-%m-%d)"
# before="$(date -v-mon -v-sun +%Y-%m-%d)"

## GNU date
# after="$(date -d "last Monday -1 week")"
# before="$(date -d "last Sunday")"
after="last Monday -1 week"
before="last Sunday"

# git log --since="last Monday 00:00" --before="Sunday 23:59" --author $(git config user.email)
git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --after="$after 00:00" --before="$before 23:59" --author $(git config user.email)