#!/usr/bin/env bash

# git unwip
#
# Rollback the previous commit if it was a WIP commit
#

if [ -z "$(git log -n 1 --format="%s" | grep -q -c -E "^WIP:")" ]; then
  echo "Last commit is not a WIP commit"
else
  git reset HEAD~1
fi