#!/usr/bin/env bash

# See what branches are merged.
function main() {
  if [ -z "$@" ]; then
   mergeTarget=$(git branch | grep -Eo "(main|master)$")
  else
    mergeTarget=$@
  fi
  merged=$(git branch --remote --merged="$mergeTarget" | grep -v " -> " | sed 's/  origin\///')
  echo "$merged" #| xargs -I {{BRANCH}} sh -c 'echo "git push origin :{{BRANCH}}"'
}

isGitRepo && main "$@"