#!/usr/bin/env bash

# Git Squash
#
# Interactively rebase the current branches commits
# from where it was forked from its base branch (assumed
# to be develop, but can be passed as an arg),
#
# Primarily useful for tidying up before pushing and
# creating a PR.


function main() {
  if [ -z "$@" ]; then
    forkPoint = "develop"
  else
    forkPoint = "$@"
  fi
  git rebase -i --autosquash $(git merge-base --fork-point "$forkpoint" $(git rev-parse --abbrev-ref HEAD))
}

isGitRepo && main "$@"