#!/usr/bin/env bash

# git last-week
#
# Print all commits that were made by the configured user
# last calendar week
#

if [[ $PLATFORM == 'MacOS' ]]; then
  after="$(date -v-mon -v-sun -v-mon +%Y-%m-%d)"
  before="$(date -v-mon -v-sun +%Y-%m-%d)"
else
  after="last Monday -1 week"
  before="last Sunday"
fi

# git log --since="last Monday 00:00" --before="Sunday 23:59" --author $(git config user.email)
git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --after="$after 00:00" --before="$before 23:59" --author $(git config user.email)