#!/usr/bin/env bash


function label(){
  printf '%-20s' "$@"
}

function value() {
  printf "$@"
  printf "\n"
}

function getCommits() {
  echo ""
  echo "Commits"
  printf '%-20s' "First Commit"
  echo "$(git log --date-order --date="format:%d-%m-%Y" --format="%ad" | tail -1)"
  printf '%-20s' "Latest Commit"
  echo "$(git log -1 --date-order --date="format:%d-%m-%Y"  --format="%ad")"
  printf '%-20s' "Total Commits"
  echo "$(git rev-list --count HEAD)"
}

function getFiles() {
  echo ""
  echo "Files"
  printf '%-20s' "Tracked files"
  echo "$(git ls-files | wc -l)"
  printf '%-20s' "Untracked files"
  echo "$(git ls-files -io --exclude-from=.gitignore | wc -l)"
}

function getSize() {
  echo ""
  echo "Size"
  printf '%-20s' "Repo size:"
  echo "$(git ls-files | xargs -d '\n' du -ch | tail -1 | cut -f 1)"
  printf '%-20s' "Size on disk"
  echo "$(du -sh ./ | awk '{print $1}')"
}

function getBranches() {
  echo ""
  echo "Branches"
  printf '%-20s' "Local"
  echo "$(git local-branches | wc -l)"
  printf '%-20s' "Remote"
  echo "$(git remote-branches | wc -l)"
  printf '%-20s' "Stale"
  echo "$(git stale-branches | wc -l)"
}

function getContributors() {
  echo ""
  echo "Contributors"
  git contributors | head -n 5
}

getCommits
getFiles
getSize
getBranches
getContributors