#!/usr/bin/env bash

## Amend a commit older than the last commit. Requires an abbreviated commit ID

function main() {
  if [ -z "$@" ]; then
    echo "fatal: no commit id supplied"
    exit 1
  fi
  TARGET=$(git rev-parse "$@")
  git commit --fixup=$TARGET && GIT_EDITOR=true git rebase --interactive --autosquash $TARGET~
}

isGitRepo && main "$@"