#!/usr/bin/env bash

# Git Squash
#
# Interactively rebase the current branches commits
# from where it was forked from its base branch (assumed
# to be develop, but can be passed as an arg),
#
# Primarily useful for tidying up before pushing and
# creating a PR.


function main() {
  git rebase -i --autosquash $(git merge-base --fork-point "$@" $(git rev-parse --abbrev-ref HEAD))
}

if [ -z "$@" ]; then
  main "develop"
else
  main "$@"
fi