#!/usr/bin/env bash

# git today
#
# Print all commits that were made by the configured user
# today
#

today=$(date +%Y-%m-%d 00:00)

git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --since="today" --author $(git config user.email)