#!/usr/bin/env bash

#
# Publish current untracked branch
#

if ! git rev-parse --abbrev-ref --symbolic-full-name $(git branch-name); then
  git push --set-upstream origin $(git branch-name)
else
  git push
done