#!/usr/bin/env bash

# git yesterday
#
# Print all commits that were made by the configured user
# yesterday
#

git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --since="yesterday 00:00"  --author $(git config user.email)