#!/usr/bin/env bash

# git this-week
#
# Print all commits that were made by the configured user
# since Monday of this week
#

git log --format='%C(dim)%cd (%h)%Creset%n  %s' --date="format:%d-%m-%Y" --no-merges --branches="*" --since="last Monday" --author $(git config user.email)