#!/usr/bin/env bash

# git this-year
#
# Print all commits that were made by the configured user
# since the first of January this year
#

lastYear=$(date -d "last Year" +%Y)
  git log --since="$lastYear-01-01 00:00" --before="$lastYear-12-31 23:59" --author $(git config user.email)