set nocompatible
set backspace=indent,eol,start
filetype plugin indent on
set backspace=2

"Set up plug.vim
call plug#begin('~/dotfiles/vim/plugged')

"NERDTree
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'trevordmiller/nova-vim'
Plug 'w0rp/ale'
call plug#end()

autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif

"Linters
let g:ale_linters = {
\   'javascript': ['eslint'],
\   'scss': ['sass-lint'],
\}
let g:ale_sign_warning = '⚠'
hi ALEWarningSign guifg=#F2C38F
let g:ale_sign_error = '✖'
hi ALEErrorSign guifg=#DF8C8C

"UI
colorscheme nova-with-italics
set ruler
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey
set showcmd
set number
syntax on

"Search stuff
set smartcase
set ignorecase
set autoread
set hlsearch
set showmatch

"Stop 'backups'
set nobackup
set noswapfile
set nowb

"Indentation stuff
set autoindent
set smartindent
set shiftwidth=4
set softtabstop=4

"Code Folding
set foldmethod=indent
set foldlevel=99 "Stop everything being folded when opened

"NERDTree Stuff
nnoremap <Leader>f :NERDTreeToggle<Enter>
let g:NERDTreeHijackNetrw = 1
let g:NERDTreeWinPos = "left"
"let g:NERDTreeMapOpenVSplit = '<CR>'
"let g:NERDTreeQuitOnOpen = 'false'
