-- set incsearch     -- Incrementally highlight search results
-- set hlsearch      -- Keep matches highlighted.
-- set ignorecase    -- Make search case insensitive
-- set smartcase     -- Use smartcase when searching